### ISSUE TITLE
Change output format

### ISSUE THREAD

**Issue by javiredracing** [ITERSA/BluetoothConnect#6]
Puntos en el ITER | Usuario | 16:05:16 11-05-2018
Lat: 28.071607 | Long: -16.513549 | Alt: 90.6 | Error: 3.2 m

12:33:15 TAM:23.40,HAM:50.10,DIS:6,ANA:[A00:4.63_A01:5.00_A02:4.12_A03:3.44],LIC:[celltemp:5.1757903e1_cellpres:1.0229817e2_co2:6.1865563e2_co2abs:8.9456882e-2_ivolt:1.2172241e1_raw:2549511.1881901],Lat:28.071607,Long:-16.513549,Alt:90.6,Error:23.2

RangoCo2:0_51 | Pendiente(*K):-0.48904 | CoeficienteCorrelacion(R2):0.09138

**Comment by aapemar** [comment]
La trama de salida es correcta, Thanks Javi ;)
